repos:
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        args: [--safe]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-added-large-files
  - id: check-yaml
  - id: check-case-conflict
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-ast
